version: '3.8'

services:
  # PostgreSQLデータベース
  db:
    image: postgres:16-alpine
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: drizzlepass
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.jsアプリケーション（開発環境）
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: blog_nextjs_dev
    restart: always
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:drizzlepass@db:5432/postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: